// src/data.js
export const properties = [
    {
      id: 1,
      title: "Spacious Apartment",
      location: "City Center",
      price: 1500,
      bedrooms: 2,
      bathrooms: 1,
      amenities: ["Swimming Pool", "Gym", "Parking"],
    },
    {
        id: 2,
        title: "Cozy Studio",
        location: "Suburbia Heights",
        price: 900,
        bedrooms: 1,
        bathrooms: 1,
        amenities: ["Parking"],
      },
      {
        id: 3,
        title: "Luxury Villa",
        location: "Oceanfront",
        price: 3000,
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Swimming Pool", "Gym", "Spa", "Ocean View"],
      },
      {
        id: 4,
        title: "Modern Loft",
        location: "Downtown Loft District",
        price: 1800,
        bedrooms: 1,
        bathrooms: 2,
        amenities: ["Gym", "Roof Terrace"],
      },
      {
        id: 5,
        title: "Countryside Retreat",
        location: "Rural Area",
        price: 1200,
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Garden", "Fireplace"],
      },
      {
        id: 6,
        title: "Urban Condo",
        location: "City Center",
        price: 2200,
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Gym", "Balcony"],
      },
      {
        id: 7,
        title: "Charming Cottage",
        location: "Village Green",
        price: 1100,
        bedrooms: 2,
        bathrooms: 1,
        amenities: ["Fireplace"],
      },

  ];
  